[project]
name = "acatiestier"
version = "0.1.0"
description = "Acatistier"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4",
    "python-docx",
    "requests>=2.32.5",
]
